import Head from "next/head";
import { getLogger } from "../logging/log-util";
import styles from "../styles/Home.module.css";

export default function Home() {
  const logger = getLogger("home");
  logger.error("a error message from Home");
  logger.debug("a debug message from Home");
  logger.info("a info message from Home");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
}
